version: '3'

services:
  springboot-docker-compose-app-container:
    image: app:1
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /data/app
    ports:
      - "8080:8080"
